### ISSUE TITLE
Upgrade to Kotlin 1.4

### ISSUE THREAD

**Issue by jeggy** [aPureBase/KGraphQL#113]
We should upgrade to Kotlin 1.4 and make this our main focus for all future releases of KGraphQL.

Point of this issue is to gather information about what is needed to do before we have fully moved to 1.4.
People are welcome to just try and clone this project and see what happens if we upgrade to 1.4 and report back here on what's needed 😃

**Comment by jeggy** [comment]
Just a note: Something that I have been thinking about is re-doing a lot of the internals to depend on the new `typeOf<T>()` function so we can easily inspect all types. (This doesn't have to be in the initial 1.4 supported release)

**Comment by NathanPB** [comment]
Kotlin 1.5 is out :eyes:

**Comment by jeggy** [comment]
Upgraded to `1.5` in version `0.17.9`
