### ISSUE TITLE
Ktor plugin recieve text in ISO-8859-1

### ISSUE THREAD

**Issue by popsa85** [aPureBase/KGraphQL#117]
**How to reproduce ?**
```
    data class Message(val message:String)
    
    install(GraphQL) {
        schema {
            type<Message>()
            query("message") {
                resolver { msg:String ->
                    Message(msg)
                }
            }
        }
    }
```
Query:
```
query {
  message(msg:"Привет"){
    message
  }
}
```
Response:
```
{
  "data": {
    "message": {
      "message": "ÐÑÐ¸Ð²ÐµÑ"
    }
  }
}
```
**Solution:**
https://github.com/aPureBase/KGraphQL/blob/4e09160f8a88c69aafb39af1a716d52ec4fa26e5/kgraphql-ktor/src/main/kotlin/com/apurebase/kgraphql/KtorFeature.kt#L58
Use:
`call.receiveStream().bufferedReader(charset = Charsets.UTF_8).readText()`
instead of call.receiveText()

**Comment by jeggy** [comment]
This is a client issue. You should make sure that your client is sending the correct HTTP headers.
To get it to work you just need to make sure your `Content-Type` header is `application/json; charset=utf-8` and then it should work.

**Comment by popsa85** [comment]
Thanks. You're right. It is very strange that Apollo Client does not specify the encoding in the header.
