### ISSUE TITLE
Can't open the project properly in kgraphql

### ISSUE THREAD

**Issue by Digital-Nomad** [aPureBase/KGraphQL#153]
I am trying to run the sample code in Jetbrain's IDEA(212.446.7)Ultimate and it's not importing correctly. Can't configure run. What version did you use to compile the project?

**Comment by jeggy** [comment]
Could you provide some more details?
What sample code are you referring to?

**Comment by Digital-Nomad** [comment]
When I open the project in idea - there's no configuration to run the code. Maybe it's a conflicting idea version - not sure though.

I am talking about the `kgraphql-example` code within this repository. I had to create a new project to try to run the code and all I am getting is a blank screen at the graphql endpoint. I can't seem to get the example code to run properly.

**Comment by jeggy** [comment]
![image](https://user-images.githubusercontent.com/51459/124802773-3dac1e80-df50-11eb-9555-21b8a049df72.png)

If you open the `Application.kt` file, can you see the play button there?

**Comment by Digital-Nomad** [comment]
I deleted and reopened the project and not the green arrow shows up and the project is configured correctly. Before the list of project files in the left panel was all highlighted yellow. Not what went wrong with the first time opening it.
