### ISSUE TITLE
Nested Fragments fail with property does not exist

### ISSUE THREAD

**Issue by jeggy** [aPureBase/KGraphQL#16]
Copied from: https://github.com/pgutkowski/KGraphQL/issues/50

**Comment by nidomiro** [comment]
I would say this is fixed with pgutkowski#51
test is here: https://github.com/aPureBase/KGraphQL/blob/1acfb4ccbc4ce5c0195c79aa27f7c7950f2d763a/src/test/kotlin/com/apurebase/kgraphql/integration/QueryTest.kt#L175
