### ISSUE TITLE
Property __typename does not exist in Query and Mutation

### ISSUE THREAD

**Issue by adi9090** [aPureBase/KGraphQL#215]
Adding __typename as a parameter in query or mutation is not working

```
  query heroes{
    __typename
  }
  
  mutation add {
    __typename
  }
```
These will return an errors:
Property __typename on Query does not exist
Property __typename on Mutation does not exist

**Comment by stuebingerb** [comment]
fyi, this has been fixed in https://github.com/stuebingerb/KGraphQL/commit/b279b059497b3385e25fedbb8d79bd2478a4d7bc
