### ISSUE TITLE
Access to requested properties

### ISSUE THREAD

**Issue by jeggy** [aPureBase/KGraphQL#40]
It would be nice to get access to the requested properties, so I for example could build SQL queries based on this.

**Comment by AlexeySoshin** [comment]
I was looking for the same feature.
Where did you think to put those properties? 
On the `Context`, maybe?

**Comment by jeggy** [comment]
I'm thinking instead of putting it onto the `Context` object you could request for it specifically, just like you do with the `Context`. Where you would be able to get access to the [Execution](https://github.com/aPureBase/KGraphQL/blob/master/kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/execution/Execution.kt) object. 

Then you would be able to create a resolver something like this

```kotlin
data class MyType(
    val id: Int,
    val value1: String?,
    val value2: String?
)
query("value") {
    resolver { execution: Execution ->
        val fields: Map<String, SelectionNode.FieldNode> = (execution.selectionNode as SelectionNode.FieldNode)
            .selectionSet!!
            .selections
            .filterIsInstance<SelectionNode.FieldNode>()
            .associateBy { it.name.value }

        val loadedValue = MyType(
            id = 1000,
            value1 = if (fields.containsKey("value1")) "Loaded value" else null,
            value2 = if (fields.containsKey("value2")) "Loaded value" else null
        )
        println(loadedValue)
        loadedValue
    }
}
```

**Comment by AlexeySoshin** [comment]
I'll take a look at that.
