### ISSUE TITLE
Type mutation must define one or more fields.

### ISSUE THREAD

**Issue by Oxymoron290** [aPureBase/KGraphQL#47]
When using [graphql-cli](https://github.com/graphql-cli/graphql-cli) to do query introspection on my endpoint I get the error `GraphQL endpoint generated invalid schema: Type mutation must define one or more fields.`.

I am using KGraphQL v0.6.2 and I do not have mutations designed for my endpoint.

Any ideas how I can have query-only schema (no mutations) using KGraphQL?

Here is my schema definition:

```
class SandDriveSchema(private val storage: SandDriveDataContext) {
    val schema = schema {
        configure {
            useDefaultPrettyPrinter = true
        }

        query("well") {
            resolver { id: Int ->
                transaction {
                    storage.getWell(id).toModel()
                }
            }
        }

        query("truckload") {
            resolver { id: Int ->
                transaction {
                    storage.getTruckLoad(id).toModel()
                }
            }
        }

        query("user") {
            resolver { id: Int ->
                transaction {
                    storage.getUser(id).toModel()
                }
            }
        }

        type<Location>()
        type<SandType>()
        type<Stage>()
        type<TruckLoad>()
        type<TruckLoadEvent>()
        type<User>()
        type<UserLocation>()
        type<Well>()
    }
}
```

**Comment by Oxymoron290** [comment]
For now I've added the following snippet to my schema. But it's smelly and I'm curious if a better solution exists.

```
        mutation("_"){
            resolver {
                -> true
            }
        }
```

**Comment by jeggy** [comment]
Sorry to say that currently there is no better solution.

This seems like an easy fix, so I will see if I can easily fix this

**Comment by jeggy** [comment]
Sorry I never got around to do this. 

Thanks to [Allali84](https://github.com/Allali84) for fixing this. You can get this on the 0.7.1 release
