### ISSUE TITLE
Better CI Testing environment

### ISSUE THREAD

**Issue by jeggy** [aPureBase/KGraphQL#50]
Currently we are using GitLab and this isn't working for GitHub forks.

There is also some issue resulting in no tests being run as seen [here on GitLab](https://gitlab.com/apurebase/kgraphql/-/jobs/258533716)

What we want:
* [x] Able to run tests against Pull Requests
* [x] Publish new versions when creating a new tag
* [x] Build & Deploy documentation site

**Comment by AlexeySoshin** [comment]
Is this still relevant?

Seems like the CodeBeat at least works.

**Comment by jeggy** [comment]
We're using CodeBeat as the previous maintainer had that setup. It doesn't test the code it just creates a code analysis of readability and stuff like that. Which is also great 😃 

Currently I'm using GitLab to publish new versions when a new git tag is created. I'm thinking we should completely drop depending on GitLab and only use GitHub Actions instead.

**Comment by AlexeySoshin** [comment]
Do you have a preference to GitHub Actions over CircleCI, or is GitHub Actions just an example?

**Comment by jeggy** [comment]
I'm thinking GitHub Actions, so we'll be as little as possible depending on external tools and now with all recent updates GitHub Actions is super flexible.

Currently I'm also using the GitLab Pages functionality which is where the documentation site is hosted on. So I'll also need to figure out how to host it on GitHub.

**Comment by jeggy** [comment]
We have now fully moved over to GitHub actions :+1:
