### ISSUE TITLE
Variables are not supported

### ISSUE THREAD

**Issue by Oxymoron290** [aPureBase/KGraphQL#51]
When creating a query like the following, I get a 500 error.

```
{
    "query":"query($id: Int!)
    {
        TruckLoad(id: $id){
            id
            truckload{id}
        }
    }",
    "variables":{
	"id": 5
    }
}
```

The endpoint throws an exception about a null argument

`com.apurebase.kgraphql.RequestException: argument id is not optional, value cannot be null`

However, if I specify a default variable, like the following, the endpoint returns, but only using the default value (`2` in this example) instead of the defined variable (`5` in this example)

```
{
    "query":"query($id: Int! = 2)
    {
        TruckLoad(id: $id){
            id
            truckload{id}
        }
    }",
    "variables":{
	"id": 5
    }
}
```

**Comment by jeggy** [comment]
how are you calling `.execute()` ?

Passing variables is split into 2 different arguments.

Here's an example:
```kotlin
val d = "\$"

val query = """
    query(${d}id: Int! = 6){
        TruckLoad(id: ${d}id) {
            id
            TruckLoad{
                id
            }
        }
    }""".trimIndent()
val variables = """
    {
        "id": 5
    }
""".trimIndent()

val res = schema.execute(query, variables)

println(res)
```

**Comment by Oxymoron290** [comment]
Using ktor:
```
routing {
    route("/graphql") {
        post {
            val request = call.receive<GraphQLRequest>()
            val query = request.query
            val context: ThetaContext by inject()
            val sch = ThetaSchema(context)
            val result = sch.schema.execute(query)
            call.respondText(result, io.ktor.http.ContentType.Application.Json)
        }
    }
}
```

**Comment by jeggy** [comment]
I'm planning to do a module for ktor, so in the feature you would just install KGraphQL into ktor something like this:
```kotlin
embeddedServer(...) {
    install(KGraphQL)
}
```

------

But for for you could take a look at this project: https://github.com/jeggy/ktorgraphql/blob/master/src/Application.kt#L55

**Comment by Oxymoron290** [comment]
I think I saw a PR or something about that in ktor's project. do you have a link?

**Comment by jeggy** [comment]
I've seen some that are using the java implementation of GraphQL. But I haven't seen any for KGraphQL. 
I'm gonna do one that is specifically made for KGraphQL

**Comment by Oxymoron290** [comment]
Awesome. also, trying your solution it shows that `request` does not have properties for `mutation` or `variables`
![image](https://user-images.githubusercontent.com/2234419/64873613-0fd54780-d60f-11e9-8b98-c9d540d60009.png)

Using v0.6.6

**Comment by Oxymoron290** [comment]
I'm sorry, I got confused
Found what I needed here - https://github.com/jeggy/ktorgraphql/blob/master/src/GraphQLRequest.kt
