### ISSUE TITLE
Confusing `Generic types are not supported by GraphQL` error with Array

### ISSUE THREAD

**Issue by Strum355** [aPureBase/KGraphQL#55]
`com.apurebase.kgraphql.schema.SchemaException: Generic types are not supported by GraphQL, found kotlin.Array<"XYZ">` is thrown when using data classes that have `Array<xyz>` as parameters. Changing the parameters to `List<xyz>` instead of `Array<xyz>` fixes the issue, but is very confusing given that List is also generic 

Edit: further inspection shows this is because Array mustnt implement Iterable. Is there a possibility that support for Array could be added?

**Comment by jeggy** [comment]
Thanks for the report 👍 

This has been fixed and java array support is available in version 0.8.1

**Comment by Strum355** [comment]
Great, thanks!
