### ISSUE TITLE
QueryOrMutationDSL.resolver(function) Support 7, 8, 9 parametres in function

### ISSUE THREAD

**Issue by orangefiredragon** [aPureBase/KGraphQL#57]
fun <T, R, E, W, Q, A, S, B>resolver(function: suspend (R, E, W, Q, A, S, B) -> T) = resolver(FunctionWrapper.on(function))

fun <T, R, E, W, Q, A, S, B, U>resolver(function: suspend (R, E, W, Q, A, S, B, U) -> T) = resolver(FunctionWrapper.on(function))

fun <T, R, E, W, Q, A, S, B, U, C>resolver(function: suspend (R, E, W, Q, A, S, B, U, C) -> T) = resolver(FunctionWrapper.on(function))

**Comment by jeggy** [comment]
This will be included in the next release 👍
