### ISSUE TITLE
Creating two fragments with same name should result in error or warning

### ISSUE THREAD

**Issue by nidomiro** [aPureBase/KGraphQL#58]
Currently the Query 
```
{
    film {
        ...film_title
    }
}

fragment film_title on Film {
    title
}

fragment film_title on Film {
    director {
        name
        age
    }
}
```
creates no error, but I think it should there should be at least a warning.
Here it's an error: https://metaphysics-production.artsy.net/?query=fragment%20a%20on%20Article%20%7B%0A%20%20id%0A%7D%0A%0Afragment%20a%20on%20Article%20%7B%0A%20%20cached%0A%7D%0A%0A%7B%0A%20%20article(id%3A%20%22%22)%7B%0A%20%20%20%20...a%0A%20%20%7D%0A%7D

**Comment by jeggy** [comment]
This has been merged and is released under version `0.9.2`
