### ISSUE TITLE
Syntax Error when leaving field list empty

### ISSUE THREAD

**Issue by FabioGimmillaro** [aPureBase/KGraphQL#67]
Hi :)

I have a little issue within my server application after updating kgraphql from 0.8.1 to 0.9.1.
When calling a mutation function with an empty field list, kgraphql throws a _GraphQLError: Syntax Error: Expected Name, found "}"._
The mutation function handles a deletion of multiple objects within my database and in this case the client doesnt care about the return value of the mutation.
The mutation gets and returns a List of UUIDs. I also tried mapping the UUIDs to Strings but that didnt solve the problem either.

The mutation looks like this:
```graphql
{
    "query": "mutation($ids: [UUID!]!) {
        r0: bulkDelete(value: $ids){
            # **This is empty**
        }
     }",
    "variables": "{
            "ids":[\"2828e080-d128-4c57-bcd8-6345007ed78e\",\"2a2283fc-fd6b-4e69-a660-66f188c2ace9\",\"70fccd23-5f96-429b-be54-87e1f8dd5d38\",\"7675f9c2-305f-4251-8d82-65dc6e5a9265\",\"7d4d1251-370f-4ea7-9b02-cd712205ea03\"]
        }"
}
```

This mutation worked perfectly fine in version 0.8.1

**Comment by jeggy** [comment]
Sorry about this. This is because I have updated the parser to be more harsh. And by following the [protocol it states](https://graphql.github.io/graphql-spec/June2018/#sec-Leaf-Field-Selections): `The subselection set of that selection must NOT BE empty`

You can solve this easily by making `bulkDelete` return a boolean instead of some object. You could also solve it by adding `id` to your selection set without actually using it in the client.

````graphql
{
    "query": "mutation($ids: [UUID!]!) {
        r0: bulkDelete(value: $ids){
            id
        }
     }",
    "variables": "{
            "ids":[\"2828e080-d128-4c57-bcd8-6345007ed78e\",\"2a2283fc-fd6b-4e69-a660-66f188c2ace9\",\"70fccd23-5f96-429b-be54-87e1f8dd5d38\",\"7675f9c2-305f-4251-8d82-65dc6e5a9265\",\"7d4d1251-370f-4ea7-9b02-cd712205ea03\"]
        }"
}
```

**Comment by FabioGimmillaro** [comment]
Hi @jeggy,

sorry I didn't know this was intended behavior. I also saw in GraphiQL that it is a common way to wrap the result into an object + information for error handling and so on.

Thanks for your Help :)
